// <auto-generated />
using System;
using BaresFamilia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaresFamilia.Infrastructure.Migrations.Nube
{
    [DbContext(typeof(NubeContext))]
    [Migration("20260724123935_AddFiscalFieldsNube")]
    partial class AddFiscalFieldsNube
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("OrdenVisual");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ConfiguracionPos", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfiguracionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SucursalId", "Nombre")
                        .IsUnique();

                    b.ToTable("ConfiguracionesPos", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Impresora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TipoDispositivo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Velocidad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SucursalId", "Nombre")
                        .IsUnique();

                    b.ToTable("Impresoras", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ImpresoraTicketTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImpresoraId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("TipoTicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("TipoTicketId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ImpresoraId", "TipoTicketId")
                        .IsUnique();

                    b.ToTable("ImpresoraTicketTipos", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SucursalId", "Etiqueta")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.MetodoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereFacturaAfip")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AlicuotaIva")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorUi")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RequiereCocina")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ProductoPrecio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoVentaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoVentaId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ProductoId", "SucursalId", "TipoVentaId")
                        .IsUnique();

                    b.ToTable("ProductoPrecios", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuit")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DomicilioFiscal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaInicioActividades")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroIIBB")
                        .HasColumnType("text");

                    b.Property<int>("PuntoDeVenta")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.TipoTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TemplateContenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("TiposTicket", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.TipoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("TiposVenta", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PinAcceso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("PinAcceso");

                    b.HasIndex("RolId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.CuentasCorrientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.CuentasCorrientes.CuentaCorriente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("SaldoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("CuentasCorrientes", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadNecesaria")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ProductoId", "InsumoId")
                        .IsUnique();

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.StockSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SucursalId", "InsumoId")
                        .IsUnique();

                    b.ToTable("StockSucursales", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Seguridad.DispositivoActivacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("CodigoActivacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoActivacion")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("DispositivosActivacion", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoCaja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SucursalId");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.CierreDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResumenJson")
                        .HasColumnType("text");

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalEgresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioCierreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UsuarioCierreId");

                    b.HasIndex("CajaId", "Fecha")
                        .IsUnique();

                    b.ToTable("CierresDiarios", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TipoVentaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Estado");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("MesaId");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("TipoVentaId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("FechaContable", "Turno");

                    b.ToTable("Comandas", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.ComandaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoPreparacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("EstadoPreparacion");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ComandaItems", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ReferenciaComprobante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("Tipo");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MetodoPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("TurnoCajaId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.TurnoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiferenciaArqueo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FondoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("SyncEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("FechaApertura");

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("SyncEstado");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("FechaContable", "Turno");

                    b.ToTable("TurnosCaja", (string)null);
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ConfiguracionPos", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("ConfiguracionesPos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Impresora", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("Impresoras")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ImpresoraTicketTipo", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Impresora", "Impresora")
                        .WithMany("TicketTiposHabilitados")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.TipoTicket", "TipoTicket")
                        .WithMany("Impresoras")
                        .HasForeignKey("TipoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresora");

                    b.Navigation("TipoTicket");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Mesa", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("Mesas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Producto", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.ProductoPrecio", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Producto", "Producto")
                        .WithMany("ProductoPrecios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("ProductoPrecios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.TipoVenta", "TipoVenta")
                        .WithMany("ProductoPrecios")
                        .HasForeignKey("TipoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoVenta");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.CuentasCorrientes.CuentaCorriente", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.CuentasCorrientes.Cliente", "Cliente")
                        .WithOne("CuentaCorriente")
                        .HasForeignKey("BaresFamilia.Core.Models.Entities.CuentasCorrientes.CuentaCorriente", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.Receta", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Inventario.Insumo", "Insumo")
                        .WithMany("Recetas")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Producto", "Producto")
                        .WithMany("Recetas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.StockSucursal", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Inventario.Insumo", "Insumo")
                        .WithMany("StockSucursales")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("StockSucursales")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Seguridad.DispositivoActivacion", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Caja", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.CierreDiario", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Comanda", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.TipoVenta", "TipoVenta")
                        .WithMany("Comandas")
                        .HasForeignKey("TipoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("TipoVenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.ComandaItem", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.Comanda", "Comanda")
                        .WithMany("Items")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Producto", "Producto")
                        .WithMany("ComandaItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.MovimientoCaja", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.TurnoCaja", "TurnoCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Pago", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.Comanda", "Comanda")
                        .WithMany("Pagos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.TurnoCaja", "TurnoCaja")
                        .WithMany("Pagos")
                        .HasForeignKey("TurnoCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("MetodoPago");

                    b.Navigation("TurnoCaja");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.TurnoCaja", b =>
                {
                    b.HasOne("BaresFamilia.Core.Models.Entities.Transaccional.Caja", "Caja")
                        .WithMany("TurnosCaja")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", "Usuario")
                        .WithMany("TurnosCaja")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Impresora", b =>
                {
                    b.Navigation("TicketTiposHabilitados");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Producto", b =>
                {
                    b.Navigation("ComandaItems");

                    b.Navigation("ProductoPrecios");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Sucursal", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("ConfiguracionesPos");

                    b.Navigation("Impresoras");

                    b.Navigation("Mesas");

                    b.Navigation("ProductoPrecios");

                    b.Navigation("StockSucursales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.TipoTicket", b =>
                {
                    b.Navigation("Impresoras");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.TipoVenta", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("ProductoPrecios");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Catalogo.Usuario", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("TurnosCaja");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.CuentasCorrientes.Cliente", b =>
                {
                    b.Navigation("CuentaCorriente");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Inventario.Insumo", b =>
                {
                    b.Navigation("Recetas");

                    b.Navigation("StockSucursales");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Caja", b =>
                {
                    b.Navigation("TurnosCaja");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.Comanda", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("BaresFamilia.Core.Models.Entities.Transaccional.TurnoCaja", b =>
                {
                    b.Navigation("MovimientosCaja");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
